// Generated by `flutterfire configure` for project baber-fundation (same
// Firebase project used by apps/web). Regenerate with that command if the
// project's Firebase apps change.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DefaultFirebaseOptions have not been configured for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4ZBQaM7lXGhPCT7mRsuhuM_cxpBSRiUQ',
    appId: '1:769611437366:android:383ab68bb8ab5c9e9f4f97',
    messagingSenderId: '769611437366',
    projectId: 'baber-fundation',
    storageBucket: 'baber-fundation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE5Sijoff1qw9RmX-zQ-IxmjcHzI6tgRs',
    appId: '1:769611437366:ios:e669099474b1dd769f4f97',
    messagingSenderId: '769611437366',
    projectId: 'baber-fundation',
    storageBucket: 'baber-fundation.firebasestorage.app',
    iosClientId: '769611437366-0h0j07uate42s797tc07i3r80g7jk8uj.apps.googleusercontent.com',
    iosBundleId: 'com.baber.baberMobile',
  );
}
